### ISSUE TITLE
R version requirement

### ISSUE THREAD

**Issue by yihui** [sagirumati/EviewsR#2]
Currently the package specifies that it requires R >= 3.2.3:
https://github.com/sagirumati/EviewsR/blob/bb525c710d6ff9e134dc06ea1568b6240e470d4d/DESCRIPTION#L9

But the source code has used some R features that were introduced in R 4.x, e.g.,

https://github.com/sagirumati/EviewsR/blob/bb525c710d6ff9e134dc06ea1568b6240e470d4d/R/create_object.R#L61

and

https://github.com/sagirumati/EviewsR/blob/bb525c710d6ff9e134dc06ea1568b6240e470d4d/R/utils.R#L32

I think you need to either increase the R version requirement, or avoid using these features.

**Comment by sagirumati** [comment]
Thank you so much. I will remove the new feature to make the package compatible with the lower R versions

Thank you once again

**Comment by sagirumati** [comment]
Dear @yihui 

I updated the package.

Should I send another PR?

Thanks

**Comment by yihui** [comment]
I don't think you need to send another PR. Thanks!

**Comment by sagirumati** [comment]
Thank you
