### ISSUE TITLE
Accessing series in eviews environment

### ISSUE THREAD

**Issue by eknirba** [sagirumati/EviewsR#4]
Hello,

`export_dataframe(wf = "priv_sa_cl", source_description = data14, start_date = '1995', frequency = "q")
exec_commands(c("priv_nsa_cl.x13()  @x11arima(amdl=b) @x11()"), wf = "priv_sa_cl")
import_series(wf = "priv_sa_cl", page = "Priv_sa_cl", series = "priv_nsa_cl")
eviews$Priv_sa_cl |>
  head()`

When I try to access my series with `eviews$Priv_sa_cl |> head()` it returns `NULL`. How should I go about it in the right way?

**Comment by sagirumati** [comment]
Thank you for your interest in the package.

Let me try and get back to you

**Comment by sagirumati** [comment]
I figured out the issue.

EviewsR is designed to convert all imported EViews object to small letters. Please try the following get back to me.

`eviews$priv_sa_cl |> head()`

Thank you

**Comment by eknirba** [comment]
I see. That worked! Thank you so much.

Anete

**Comment by eknirba** [comment]
That worked! Thanks!
